jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set working directory
        run: cd OreESP_Template

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Use local Gradle 4.10.3
        run: |
          export PATH="$HOME/Downloads/gradle-4.10.3/bin:$PATH"
          gradle -v

      - name: Clean build
        run: |
          cd OreESP_Template
          ./gradlew clean

      - name: Setup workspace
        run: |
          cd OreESP_Template
          ./gradlew setupDecompWorkspace

      - name: Build OreESP.jar
        run: |
          cd OreESP_Template
          ./gradlew build

      - name: Upload OreESP.jar
        uses: actions/upload-artifact@v4
        with:
          name: OreESP
          path: OreESP_Template/build/libs/*.jar
