name: Build OreESP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    name: Build on Mac self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Use local Gradle 4.10.3
        run: |
          export PATH="$HOME/Downloads/gradle-4.10.3/bin:$PATH"
          gradle -v

      - name: Clean build
        run: ./gradlew clean

      - name: Setup workspace
        run: ./gradlew setupDecompWorkspace

      - name: Build OreESP.jar
        run: ./gradlew build

      - name: Upload OreESP.jar
        uses: actions/upload-artifact@v4
        with:
          name: OreESP
          path: build/libs/*.jar
